name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'server/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Retrieve vscode icons
        uses: actions/checkout@v2
        with:
          repository: 'vscode-icons/vscode-icons'
          path: 'vscode-icons'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache deps
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          yarn

      - name: Build
        run: |
          make build

      - name: Test
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: yarn test
